export const GET_MEDICAL_START = 'GET_MEDICAL_START';
export const GET_MEDICAL_END = 'GET_MEDICAL_END';
export const GET_MEDICAL_SUCCESS = 'GET_MEDICAL_SUCCESS';
export const GET_MEDICAL_FAILURE = 'GET_MEDICAL_FAILURE';
